[package]
name = "doc_search"
version = "0.1.0"
edition = "2024"
excldue = ["test_data/"]

[dependencies]
clap = { version = "4.5.58", features = ["derive"] }
litchi = { version = "0.0.1", features = ["odf"] }
tempfile = "3.25.0"
walkdir = "2.5.0"
